add new built-in format
invopop/jsonschema pull request #44
Opened 2022-09-08 02:59 UTC by haoel

Add the `date`, `time`, `duration` iri` new format
refer to: https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats

2022-09-29 11:38 UTC, samlown requested changes
This makes a lot of sense, but I do think we should have some tests to validate these use-cases.

2022-11-08 08:57 UTC, samlown commented
Thanks for the tests! Looks great! Just a few linting issues.

2022-11-10 03:45 UTC, haoel commented
done!

2022-11-12 03:28 UTC, webdestroya commented
shouldn't it be `BuiltInFormat` rather than `BuildInFormat` ?

2022-11-15 09:38 UTC, haoel commented
please approve running the workflows, I believe I fix the lint errors.

2023-06-08 07:57 UTC, amiramw commented
is there a plan to merge this PR?

2025-05-05 16:40 UTC, rslobodian commented
+1 to this PR. 
@samlown any plans to getting this merged?

2026-04-23 14:08 UTC, samlown commented
This was solved in #111. Thanks.

2026-04-23 14:08 UTC, closed without merging