Fix anonymous ptr to struct inlining
invopop/jsonschema pull request #47
Opened 2022-09-16 12:49 UTC by paulcacheux

As can be shown in https://go.dev/play/p/4qEwn5yKzFj, JSON marshal rules also inline anonymous pointer to struct.

This PR implements this feature and add a test for this.

2022-09-23 19:45 UTC, paulcacheux commented
@samlown can you take a look at this ? Thanks !

2022-09-23 20:12 UTC, samlown requested changes
Looks like the tests are failing...

2022-09-23 20:20 UTC, paulcacheux commented
Oh yes it's because `Pointer` is only available on recent go versions, I fixed this in the last commit

2022-09-23 21:00 UTC, samlown approved these changes
Cool thanks!

2022-09-23 21:00 UTC, merged

2022-10-01 12:09 UTC, paulcacheux commented
@samlown do you plan to create a release tag for this ? Or are you waiting on something else ?