Fix tag parsing
invopop/jsonschema pull request #7
Opened 2022-02-16 13:48 UTC by gutjuri

I already opened an issue and a PR in the original repo of this project (see https://github.com/alecthomas/jsonschema/issues/117). 

Since this seems to be the currently maintained fork of the project, I wanted to share this bugfix with you. I'd be glad if you accepted it.

I'm open for criticism and comments.

2022-02-16 23:15 UTC, samlown requested changes
This for sure is useful! In addition to my comment, I'd suggest adding some direct unit tests for the method to test out several scenarios. I don't think you need a full schema example for this one.

Also, we're currently working on a major refactor to move to JSON Schema Draft 2020-12. It'd be great if you could update your PR afterwards! Should be a simple merge for this use-case. Thank you!!

2022-02-16 23:15 UTC, samlown commented on reflect.go
> +		if lastRune == ',' && unicode.IsLetter(chr) {
I have doubts about this approach. There is no guarantee that the next character after a comma is the separator. Have you tried using an escape character? i.e. `\`. You could then split on an regexp instead, with a pattern like `[^\\],`.

2022-02-17 11:21 UTC, gutjuri commented
I updated my PR but it won't show up in this thread, because GH no longer considers this repo a fork of alecthomas/jsonschema. I'll refork and submit a new PR.

2022-02-17 11:24 UTC, samlown commented
> I updated my PR but it won't show up in this thread, because GH no longer considers this repo a fork of alecthomas/jsonschema. I'll refork and submit a new PR.

You should able to just re-assign the PR to a new branch in the new repo, but please do what you think is easiest!

2022-02-17 11:46 UTC, gutjuri commented
see #8 now

2022-02-17 11:46 UTC, closed without merging